spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/listywave;MODE=MySQL
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

cors:
  allowedOrigins:

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.orm.transaction: DEBUG
    org.apache.coyote.http11: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace # 쿼리 파라미터 로그 남기기

cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
  s3:
    endpoint:
    bucket:

jwt:
  plain-secret-key:
