spring:
  profiles:
    group:
      local: "local"
      dev: "dev, datasource"
    include:
      - security

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
      show-sql: true
