spring:
  datasource:
    url: jdbc:mysql://localhost:3306/listywave
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

cors:
  allowedOrigins:

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.orm.transaction: DEBUG
    org.apache.coyote.http11: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace # 쿼리 파라미터 로그 남기기

cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
  s3:
    endpoint:
    bucket:

jwt:
  plain-secret-key:
  issuer: "http://localhost.com"
  access-token-valid-time-duration: 30
  access-token-valid-time-unit: MINUTES
  refresh-token-valid-time-duration: 2
  refresh-token-valid-time-unit: HOURS

