version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/ # elasticsearch 전용 Dockerfile을 가져와 빌드
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      #      ELASTIC_PASSWORD: elastic
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/config/pipelines.yml # 커스텀 pipeline을 사용할 수 있게 함
        target: /usr/share/logstash/config/pipelines.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline   # 커스텀 pipeline을 바인드
        target: /usr/share/logstash/pipeline
        read_only: true
      - type: bind
        source: ./logstash/mysql-connector-j-8.0.33.jar # mysql을 연결할 수 있도록 커넥터 바인드
        target: /usr/share/logstash/logstash-core/lib/jars/mysql-connector-j-8.0.33.jar
    ports:
      - "5044:5044"
      - "9600:9600"
      - "9900:9900"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
