package com.listywave.list.application.domain.list;

public enum BackgroundColor {

    PASTEL_PINK,
    PASTEL_ORANGE,
    PASTEL_YELLOW,
    PASTEL_GREEN,
    PASTEL_SKYBLUE,
    PASTEL_PURPLE,

    VIVID_RED,
    VIVID_ORANGE,
    VIVID_YELLOW,
    VIVID_GREEN,
    VIVID_BLUE,
    VIVID_PURPLE,

    GRAY_VERYLIGHT,
    GRAY_LIGHT,
    GRAY_MEDIUM,
    GRAY_SOFT_BLUE,
    GRAY_LIGHT_BLUE,
    GRAY_MEDIUM_BLUE,

    NEON_WHITE,
    NEON_YELLOW,
    NEON_ORANGE,
    NEON_GREEN,
    NEON_BLUE,
    NEON_PURPLE,
}
