name: CI workflow

on:
  pull_request:
    branches: [ "dev", "prod" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: 체크아웃
        uses: actions/checkout@v4

      - name: JDK 셋업
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          cache: 'gradle'
          distribution: 'corretto'

      - name: Gradle 셋업, 빌드, 캐시
        uses: burrunan/gradle-cache-action@c15634bb25b7284dc084f38dff4e838048b7feaf
        with:
          arguments: build
          properties: |
            --build-cache
            --parallel
