name: CI workflow

on:
  pull_request:
    branches: [ "dev", "prod" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4.1.4
      - uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          cache: 'gradle'
          distribution: 'corretto'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.12.0
        with:
          arguments: build

      - run: ./gradlew build
