name: deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main", "dev" ]
    
jobs:
  deploy:
    runs-on: self-hosted
    env:
      working-directory: /home/ubuntu
    steps:
      - run: pwd
      - run: ./listywave.sh deploy
