name: deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main", "dev" ]
    
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: check current position
        working-directory: /home/ubuntu
        run: pwd
      - name: run deploy script
        working-directory: /home/ubuntu
        run: ./listywave.sh deploy
