name: Deploy to DEV

on:
  workflow_dispatch:
  push:
    branches: [ "dev" ]

permissions:
  contents: read
    
jobs:
  deploy:
      runs-on: self-hosted

      steps:
        - name: Run Deploy script
          working-directory: /home/ubuntu
          run: sudo ./listywave.sh deploy
